[package]
name = "rust-mongodb"
version = "0.1.0"
authors = ["Irina Shestak <shestak.irina@gmail.com>"]

[dependencies]
bson = "0.12.1"
mongodb = "0.3.9"
serde_json = "1.0"
serde = "1.0.70"
serde_derive = "1.0.70"
